<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>addProduct</title>
</head>
<body>
    <form action="index.php" method="post">
        <label for="name">Name:</label>
        <input type="text" id="name" name="name">
        <br><br>
        <label for="price">Price:</label>
        <input type="number" id="price" name="price">
        <br><br>
        <label for="description">Description:</label>
        <textarea id="description" name="description" cols="30" rows="10"></textarea>
        <br><br>
        <input type="submit" value="addProduct">
    </form>
 </body
    
</body>
</html>