<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>addProduct</title>
</head>
<body>
    <h2>Añadir producto</h2>
    <form action="index.php" method="post">
        Name:
        <input type="text" id="name" name="name">
        <br><br>
        Price:
        <input type="number" id="price" name="price">
        <br><br>
        Description:
        <textarea id="description" name="description" cols="30" rows="10"></textarea>
        <br><br>
        Stock:
        <input type="number" id="stock" name="stock" >
        <br><br>
        <input type="submit" value="Add Product" name="addProduct">
    </form>
 </body
    
</body>
</html>