<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>addProduct</title>
</head>
<body>
    <h2>Añadir producto</h2>
    <form action="index.php" method="post">
        Name:
        <input type="text" id="name" name="name">
        <br><br>
        Price:
        <input type="number" id="price" name="price">
        <br><br>
        Description:
        <textarea id="description" name="description" cols="30" rows="10"></textarea>
        <br><br>
        Stock:
        <input type="number" id="stock" name="stock" >
        <br><br>
        <input type="submit" value="Add Product" name="addProduct">
    </form>
    <?php if (!empty($products)): ?>
        <table border="1">
            <tr>
                <th>Nombre</th>
                <th>Precio</th>
                <th>Descripción</th>
                <th>Stock</th>
                <th>Acciones</th>
            </tr>
            <?php foreach ($products as $product): ?>
                <tr>
                    <td><?php echo htmlspecialchars($product->getName()); ?></td>
                    <td><?php echo htmlspecialchars($product->getprice()); ?></td>
                    <td><?php echo htmlspecialchars($product->getDescription()); ?></td>
                    <td><?php echo htmlspecialchars($product->getStock()); ?></td>
                    <td>
                        <a href="index.php?delete=<?php echo $product->getId(); ?>">Eliminar</a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
    <?php else: ?>
        <p>No hay productos disponibles.</p>
    <?php endif; ?>
 </body
    
</body>
</html>