<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pedido Finalizado</title>
</head>
<body>
    <h1>¡Pedido Finalizado!</h1>
    <p>Tu pedido ha sido finalizado exitosamente. Gracias por tu compra.</p>

    <!-- Link para regresar a la página principal o de productos -->
    <a href="/tiendaonlinemcv/index.php">Volver a la página principal</a>
    </body>
</html>
